### ISSUE TITLE
代码超出了框框

### ISSUE THREAD

**Issue by suntabu** [shanbufun/gridea-theme-song#1]
你好，非常喜欢你的这个主题，十分漂亮，但是现在有点问题，能修复一下么？

具体可以看我的博客首页：
https://www.suntabu.com/

不止代码超出去了，如果图片过大也会超出去。

**Comment by shanbufun** [comment]
> 你好，非常喜欢你的这个主题，十分漂亮，但是现在有点问题，能修复一下么？
> 
> 具体可以看我的博客首页：[https](https://www.suntabu.com/) :
> [//www.suntabu.com/](https://www.suntabu.com/)
> 
> 不止代码超过去了，如果图片过大也会超过去。

这回至读取文字了！但是需要最新版本0.84或者最新测试版才能支持！

**Comment by suntabu** [comment]
好的，感谢！！我在休假，等回来了验证一下。
再次感谢

**Comment by suntabu** [comment]
感觉还是原来读取代码来渲染的好看一点，谢谢你了，我自己想办法解决吧
